### ISSUE TITLE
Review port to mermaid v10

### ISSUE THREAD

**Issue by frehberg** [mersinvald/aquamarine#35]
* Deal with multiple JS files instead of single mermaid.min.js
  * see request https://github.com/mermaid-js/mermaid/issues/4203
  * see 262 files in  https://unpkg.com/browse/mermaid@10.0.2/dist/

* Change script-initialization, using the following ESM form in future
```
<script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
      ...
</script>
``` 
or accessing the local files location

To test the port, change the dependency in Cargo.toml to

```toml
[dependencies]
aquamarine = { git = "https://github.com/frehberg/aquamarine.git", branch = "35_port_mermaid_v10" }
```
